classes:
- open
- short
- mousebite
- spur
- copper
- pin-hole
detectors:
  yolov8:
    conf_threshold: 0.7
    enabled: true
    input_size: 640
    onnx_path: null
    raw_weights_path: ./weights/deeppcb/yolov8/yolov8.pt
    type: yolo
  yolov7:
    conf_threshold: 0.6
    enabled: true
    input_size: 640
    onnx_path: null
    raw_weights_path: ./weights/deeppcb/yolov7/yolov7.pt
    type: yolo
device:
  gpu_id: 0
  preferred: cuda
f1_scores:
  open:
    yolov7: 0.971
    frcnn: 0.930
    yolov8: 0.957
    rt_detrv2: 0.9915
  short:
    yolov7: 0.923
    frcnn: 0.800
    yolov8: 0.903
    rt_detrv2: 0.9474
  mousebite:
    yolov7: 0.968
    frcnn: 0.903
    yolov8: 0.973
    rt_detrv2: 0.9830
  spur:
    yolov7: 0.968
    frcnn: 0.932
    yolov8: 0.954
    rt_detrv2: 0.9907
  copper:
    yolov7: 0.975
    frcnn: 0.941
    yolov8: 0.974
    rt_detrv2: 0.9796
  pin-hole:
    yolov7: 0.957
    frcnn: 0.873
    yolov8: 0.918
    rt_detrv2: 0.9620
voter:
  conf_thresh: 0.6
  solo_strong: 0.98
  iou_thresh: 0.4
  gamma: 2.0
  f1_margin: 0.05
  near_tie_conf: 0.90
  fuse_coords: true
  use_f1: true
